repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4  # Use the version of ruff you have specified in your requirements
    hooks:
      - id: ruff-format
        name: ruff-formatter
        stages: [commit]
      - id: ruff
        name: ruff-linter
        stages: [push]
        args: ["--no-fix"]  # This will only lint without fixing
