# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.8
  install:
     - requirements: requirements/dev.txt
     - method: pip
       path: . 
  system_packages: true
